#!/usr/bin/env groovy
//
// ec2DockerComposeDeployEnv.groovy
//
def call() {
    echo "Deploying the application via Docker Compose on EC2 ... "

    sshagent(['ec2-server-key']) {
        withCredentials([
            string(credentialsId: 'EC2_USER', variable: 'EC2_USER'),
            string(credentialsId: 'EC2_HOST', variable: 'EC2_HOST')
        ]) {
            // Server Initialisation : create /opt/app and change permissions for docker
            sh """
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
                if [ ! -d /opt/app ]; then
                    sudo mkdir -p /opt/app
                    sudo chown -R $EC2_USER:docker /opt/app
                fi
            '
            """

            // Copy docker-compose.yaml + .env generated by Jenkins
            sh """
            scp -o StrictHostKeyChecking=no \
                docker-compose.yaml .env \
                $EC2_USER@$EC2_HOST:/opt/app
            """

            sh """
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
                cd /opt/app

                docker compose -f docker-compose.yaml down --remove-orphans --volumes
                docker compose -f docker-compose.yaml up -d --quiet-pull
            '
            """
        }
    }
}
